---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1
  labels:
    app: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local
