---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.13
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata  
          - name: POSTGRES_DB
            value: testdatabase
          - name: POSTGRES_USER
            value: testuser
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secure
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
          - name: pv1
            mountPath: /var/lib/postgresql/data
      volumes:      
        - name: pv1
          persistentVolumeClaim:
            claimName: pvc1
