---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-pvc-ssd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "csi-ceph-ssd-ms1"
