---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine:4.1.1
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
          - name: REDMINE_DB_POSTGRES
            value: database
          - name: REDMINE_DB_USERNAME
            value: testuser
          - name: REDMINE_DB_DATABASE
            value: testdatabase
          - name: REDMINE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secure
                key: POSTGRES_PASSWORD
          - name: REDMINE_SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: redmine-secret
                key: REDMINE_SECRET_KEY_BASE   
        ports:
        - containerPort: 3000
